In [341]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import random
import matplotlib.pyplot as plt 
%matplotlib inline

In [342]:

ecommerce_df = pd.read_csv(r'C:\Users\maram\Downloads\ecommerce dataset.csv', encoding='latin1')

In [343]:
ecommerce_df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer Name,Segment,Country,City,State,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,Claire Gute,Consumer,United States,Henderson,Kentucky,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,Claire Gute,Consumer,United States,Henderson,Kentucky,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,Darrin Van Huff,Corporate,United States,Los Angeles,California,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10000,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,Tom Boeckenhauer,Consumer,United States,Miami,Florida,Furniture,Furnishings,Ultra Door Pull Handle,25.25,3,0.20,4.10
10001,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,Dave Brooks,Consumer,United States,Costa Mesa,California,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.96,2,0.00,15.63
10002,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,Dave Brooks,Consumer,United States,Costa Mesa,California,Technology,Phones,Aastra 57i VoIP phone,258.58,2,0.20,19.39
10003,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,Dave Brooks,Consumer,United States,Costa Mesa,California,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.60,4,0.00,13.32
10004,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,Chris Cortes,Consumer,United States,Westminster,California,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.00,72.95

In [322]:
ecommerce_df.info

<bound method DataFrame.info of        Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0           1  CA-2016-152156   11/8/2016  11/11/2016    Second Class
1           2  CA-2016-152156   11/8/2016  11/11/2016    Second Class
2           3  CA-2016-138688   6/12/2016   6/16/2016    Second Class
3           4  US-2015-108966  10/11/2015  10/18/2015  Standard Class
4           5  US-2015-108966  10/11/2015  10/18/2015  Standard Class
...       ...             ...         ...         ...             ...
10000    9990  CA-2014-110422   1/21/2014   1/23/2014    Second Class
10001    9991  CA-2017-121258   2/26/2017    3/3/2017  Standard Class
10002    9992  CA-2017-121258   2/26/2017    3/3/2017  Standard Class
10003    9993  CA-2017-121258   2/26/2017    3/3/2017  Standard Class
10004    9994  CA-2017-119914    5/4/2017    5/9/2017    Second Class

          Customer Name    Segment        Country             City  \
0           Claire Gute   Consumer  United States        Henderson
1           Claire Gute   Consumer  United States        Henderson
2       Darrin Van Huff  Corporate  United States      Los Angeles
3        Sean O'Donnell   Consumer  United States  Fort Lauderdale
4        Sean O'Donnell   Consumer  United States  Fort Lauderdale
...                 ...        ...            ...              ...
10000  Tom Boeckenhauer   Consumer  United States            Miami
10001       Dave Brooks   Consumer  United States       Costa Mesa
10002       Dave Brooks   Consumer  United States       Costa Mesa
10003       Dave Brooks   Consumer  United States       Costa Mesa
10004      Chris Cortes   Consumer  United States      Westminster

            State         Category Sub-Category  \
0        Kentucky        Furniture    Bookcases
1        Kentucky        Furniture       Chairs
2      California  Office Supplies       Labels
3         Florida        Furniture       Tables
4         Florida  Office Supplies      Storage
...           ...              ...          ...
10000     Florida        Furniture  Furnishings
10001  California        Furniture  Furnishings
10002  California       Technology       Phones
10003  California  Office Supplies        Paper
10004  California  Office Supplies   Appliances

                                            Product Name  Sales  Quantity  \
0                      Bush Somerset Collection Bookcase 261.96         2
1      Hon Deluxe Fabric Upholstered Stacking Chairs,... 731.94         3
2      Self-Adhesive Address Labels for Typewriters b...  14.62         2
3          Bretford CR4500 Series Slim Rectangular Table 957.58         5
4                         Eldon Fold 'N Roll Cart System  22.37         2
...                                                  ...    ...       ...
10000                             Ultra Door Pull Handle  25.25         3
10001  Tenex B1-RE Series Chair Mats for Low Pile Car...  91.96         2
10002                              Aastra 57i VoIP phone 258.58         2
10003  It's Hot Message Books with Stickers, 2 3/4" x 5"  29.60         4
10004  Acco 7-Outlet Masterpiece Power Center, Wihtou... 243.16         2

       Discount  Profit
0          0.00   41.91
1          0.00  219.58
2          0.00    6.87
3          0.45 -383.03
4          0.20    2.52
...         ...     ...
10000      0.20    4.10
10001      0.00   15.63
10002      0.20   19.39
10003      0.00   13.32
10004      0.00   72.95

[10005 rows x 17 columns]>

In [344]:
ecommerce_df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer Name,Segment,Country,City,State,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,Claire Gute,Consumer,United States,Henderson,Kentucky,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,Claire Gute,Consumer,United States,Henderson,Kentucky,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,Darrin Van Huff,Corporate,United States,Los Angeles,California,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52

In [349]:
ecommerce_df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer Name    6
Segment          0
Country          2
City             0
State            2
Category         0
Sub-Category     0
Product Name     0
Sales            7
Quantity         0
Discount         0
Profit           0
dtype: int64

In [350]:
ecommerce_df.duplicated().sum()

10

In [351]:
df_clean = ecommerce_df.copy()

# Clean the string columns: remove leading/trailing spaces and convert to lowercase
df_clean[df_clean.select_dtypes(include='object').columns] = \
    df_clean.select_dtypes(include='object').apply(lambda col: col.str.strip().str.lower())

# Check and remove duplicates in one step
num_duplicates = df_clean.duplicated().sum()

if num_duplicates > 0:
    print(f' Number of duplicate rows: {num_duplicates}')
    print('\n Duplicate rows:')
    display(df_clean[df_clean.duplicated()])

    # Remove duplicates
    df_clean = df_clean.drop_duplicates()
    print(f'\nDuplicates removed. Number of rows now: {df_clean.shape[0]}')
else:
    print(' No duplicate rows.')

# Verify that no duplicates remain after removal
print(f'Number of duplicate rows after removal: {df_clean.duplicated().sum()}')

 Number of duplicate rows: 10

 Duplicate rows:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer Name,Segment,Country,City,State,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
5,5,us-2015-108966,10/11/2015,10/18/2015,standard class,sean o'donnell,consumer,united states,fort lauderdale,florida,office supplies,storage,eldon fold 'n roll cart system,22.37,2,0.20,2.52
15,13,ca-2017-114412,4/15/2017,4/20/2017,standard class,andrew allen,consumer,united states,concord,north carolina,office supplies,paper,xerox 1967,15.55,3,0.20,5.44
16,13,ca-2017-114412,4/15/2017,4/20/2017,standard class,andrew allen,consumer,united states,concord,north carolina,office supplies,paper,xerox 1967,15.55,3,0.20,5.44
32,28,us-2015-150630,9/17/2015,9/21/2015,standard class,tracy blumstein,consumer,united states,philadelphia,pennsylvania,furniture,bookcases,"riverside palais royal lawyers bookcase, royal...",3083.43,7,0.50,-1665.05
34,29,us-2015-150630,9/17/2015,9/21/2015,standard class,tracy blumstein,consumer,united states,philadelphia,pennsylvania,office supplies,binders,avery recycled flexi-view covers for binding s...,9.62,2,0.70,-7.05
40,34,us-2015-150630,9/17/2015,9/21/2015,standard class,tracy blumstein,consumer,united states,philadelphia,pennsylvania,office supplies,art,lumber crayons,15.76,2,0.20,3.55
43,36,ca-2016-117590,12/8/2016,12/10/2016,first class,gene hale,corporate,united states,richardson,texas,technology,phones,ge 30524ee4,1097.54,7,0.20,123.47
44,36,ca-2016-117590,12/8/2016,12/10/2016,first class,gene hale,corporate,united states,richardson,texas,technology,phones,ge 30524ee4,1097.54,7,0.20,123.47
4435,4426,ca-2017-159464,5/18/2017,5/19/2017,first class,todd boyes,corporate,united states,sandy springs,georgia,office supplies,binders,poly designer cover & back,113.94,6,0.00,54.69
4436,4426,ca-2017-159464,5/18/2017,5/19/2017,first class,todd boyes,corporate,united states,sandy springs,georgia,office supplies,binders,poly designer cover & back,113.94,6,0.00,54.69

Duplicates removed. Number of rows now: 9995
Number of duplicate rows after removal: 0

In [352]:
ecommerce_df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [353]:
df_clean = df_clean.drop_duplicates()

In [354]:
def fill_missing_with_default(df, column, default_value=0):
    """
    Fill missing values in a column with a default value (e.g., 0).
    """
    df[column] = df[column].fillna(default_value)
    return df

In [355]:
df_clean = fill_missing_with_default(df_clean, 'Discount', default_value=0)

In [356]:

ecommerce_df['Order Date'] = ecommerce_df['Order Date'].astype(str)


ecommerce_df['Order Date'] = ecommerce_df['Order Date'].str.strip("'\"")


ecommerce_df['Order Date'] = pd.to_datetime(ecommerce_df['Order Date'], errors='coerce')


print(ecommerce_df['Order Date'].head())

0   2016-11-08
1   2016-11-08
2   2016-06-12
3   2015-10-11
4   2015-10-11
Name: Order Date, dtype: datetime64[ns]

In [357]:
ecommerce_df = ecommerce_df.dropna(subset=['Customer Name'])

In [358]:
total_revenue = df_clean['Sales'].sum()
print(f'Total Revenue: {total_revenue}')

Total Revenue: 2293011.9183

In [359]:
average_sales = df_clean['Sales'].mean()
print(f'Average Sales per Order: {average_sales}')

Average Sales per Order: 229.57668385062075

In [360]:
df_clean['Discount Percentage'] = df_clean['Discount'] * 100
df_clean

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer Name,Segment,Country,City,State,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Discount Percentage
0,1,ca-2016-152156,11/8/2016,11/11/2016,second class,claire gute,consumer,united states,henderson,kentucky,furniture,bookcases,bush somerset collection bookcase,261.96,2,0.00,41.91,0.00
1,2,ca-2016-152156,11/8/2016,11/11/2016,second class,claire gute,consumer,united states,henderson,kentucky,furniture,chairs,"hon deluxe fabric upholstered stacking chairs,...",731.94,3,0.00,219.58,0.00
2,3,ca-2016-138688,6/12/2016,6/16/2016,second class,darrin van huff,corporate,united states,los angeles,california,office supplies,labels,self-adhesive address labels for typewriters b...,14.62,2,0.00,6.87,0.00
3,4,us-2015-108966,10/11/2015,10/18/2015,standard class,sean o'donnell,consumer,united states,fort lauderdale,florida,furniture,tables,bretford cr4500 series slim rectangular table,957.58,5,0.45,-383.03,45.00
4,5,us-2015-108966,10/11/2015,10/18/2015,standard class,sean o'donnell,consumer,united states,fort lauderdale,florida,office supplies,storage,eldon fold 'n roll cart system,22.37,2,0.20,2.52,20.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10000,9990,ca-2014-110422,1/21/2014,1/23/2014,second class,tom boeckenhauer,consumer,united states,miami,florida,furniture,furnishings,ultra door pull handle,25.25,3,0.20,4.10,20.00
10001,9991,ca-2017-121258,2/26/2017,3/3/2017,standard class,dave brooks,consumer,united states,costa mesa,california,furniture,furnishings,tenex b1-re series chair mats for low pile car...,91.96,2,0.00,15.63,0.00
10002,9992,ca-2017-121258,2/26/2017,3/3/2017,standard class,dave brooks,consumer,united states,costa mesa,california,technology,phones,aastra 57i voip phone,258.58,2,0.20,19.39,20.00
10003,9993,ca-2017-121258,2/26/2017,3/3/2017,standard class,dave brooks,consumer,united states,costa mesa,california,office supplies,paper,"it's hot message books with stickers, 2 3/4"" x 5""",29.60,4,0.00,13.32,0.00
10004,9994,ca-2017-119914,5/4/2017,5/9/2017,second class,chris cortes,consumer,united states,westminster,california,office supplies,appliances,"acco 7-outlet masterpiece power center, wihtou...",243.16,2,0.00,72.95,0.00

In [361]:

def categorize_customer(row):
    if row['Sales'] > 1000:
        return 'High Value'
    elif row['Sales'] > 500:
        return 'Medium Value'
    else:
        return 'Low Value'

df_clean['Customer Segment'] = df_clean.apply(categorize_customer, axis=1)
df_clean

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer Name,Segment,Country,City,State,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Discount Percentage,Customer Segment
0,1,ca-2016-152156,11/8/2016,11/11/2016,second class,claire gute,consumer,united states,henderson,kentucky,furniture,bookcases,bush somerset collection bookcase,261.96,2,0.00,41.91,0.00,Low Value
1,2,ca-2016-152156,11/8/2016,11/11/2016,second class,claire gute,consumer,united states,henderson,kentucky,furniture,chairs,"hon deluxe fabric upholstered stacking chairs,...",731.94,3,0.00,219.58,0.00,Medium Value
2,3,ca-2016-138688,6/12/2016,6/16/2016,second class,darrin van huff,corporate,united states,los angeles,california,office supplies,labels,self-adhesive address labels for typewriters b...,14.62,2,0.00,6.87,0.00,Low Value
3,4,us-2015-108966,10/11/2015,10/18/2015,standard class,sean o'donnell,consumer,united states,fort lauderdale,florida,furniture,tables,bretford cr4500 series slim rectangular table,957.58,5,0.45,-383.03,45.00,Medium Value
4,5,us-2015-108966,10/11/2015,10/18/2015,standard class,sean o'donnell,consumer,united states,fort lauderdale,florida,office supplies,storage,eldon fold 'n roll cart system,22.37,2,0.20,2.52,20.00,Low Value
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10000,9990,ca-2014-110422,1/21/2014,1/23/2014,second class,tom boeckenhauer,consumer,united states,miami,florida,furniture,furnishings,ultra door pull handle,25.25,3,0.20,4.10,20.00,Low Value
10001,9991,ca-2017-121258,2/26/2017,3/3/2017,standard class,dave brooks,consumer,united states,costa mesa,california,furniture,furnishings,tenex b1-re series chair mats for low pile car...,91.96,2,0.00,15.63,0.00,Low Value
10002,9992,ca-2017-121258,2/26/2017,3/3/2017,standard class,dave brooks,consumer,united states,costa mesa,california,technology,phones,aastra 57i voip phone,258.58,2,0.20,19.39,20.00,Low Value
10003,9993,ca-2017-121258,2/26/2017,3/3/2017,standard class,dave brooks,consumer,united states,costa mesa,california,office supplies,paper,"it's hot message books with stickers, 2 3/4"" x 5""",29.60,4,0.00,13.32,0.00,Low Value
10004,9994,ca-2017-119914,5/4/2017,5/9/2017,second class,chris cortes,consumer,united states,westminster,california,office supplies,appliances,"acco 7-outlet masterpiece power center, wihtou...",243.16,2,0.00,72.95,0.00,Low Value

In [333]:
# Save the cleaned data to a new CSV file
ecommerce_df.to_csv('clean_sales.csv', index=False)

# Print a message confirming the file has been written
print("Clean file written: clean_sales.csv")

# Print the number of rows in the cleaned data
print(f"Clean rows: {len(ecommerce_df)}")

Clean file written: clean_sales.csv
Clean rows: 9999